ESCAPES_TAG = 'ESCAPES'

ESCAPE_NAME_TAG = 'NAME'
ESCAPE_SHORT_NAME_TAG = 'SHORT_NAME'
ESCAPE_ADDRESS_TAG = 'ADDRESS'
ESCAPE_PHONE_TAG = 'PHONE'
ESCAPE_WEBSITE_TAG = 'WEBSITE'
ESCAPE_LAT_TAG = 'LAT'
ESCAPE_LON_TAG = 'LON'
ESCAPE_TAGS_TAG = 'TAGS'
ESCAPE_CODE_TAG = 'CODE'

ROOMS_TAG = 'ROOMS'

ROOMS_NAME_TAG = 'NAME'
ROOMS_WEBSITE_TAG = 'WEBSITE'
ROOMS_PRICES_TAG = 'PRICES'
ROOMS_AVAIL_TAG = 'AVAIL'
ROOMS_CODE_TAG = 'CODE'

SEPARATOR = '%'

HORROR_TAG = "horror"
ACTORS_TAG = "attori"
ADVENTURE_TAG = "avventura"
MISTERY_TAG = "mistero"
