# links to JSON bin
ESCAPE_BIN = "https://api.jsonbin.io/b/5ee3bb1c1f9e4e57881c6bbe"
ESCAPE_BIN_LATEST = "https://api.jsonbin.io/b/5ee3bb1c1f9e4e57881c6bbe/latest"
TIME_BIN = "https://api.jsonbin.io/b/5ee3e9651f9e4e57881c8189"
TIME_BIN_LATEST = "https://api.jsonbin.io/b/5ee3e9651f9e4e57881c8189/latest"

# JSON fields
DB_TIME = 'TIME'

ESCAPES_TAG = 'ESCAPES'

ESCAPE_NAME_TAG = 'NAME'
ESCAPE_SHORT_NAME_TAG = 'SHORT_NAME'
ESCAPE_ADDRESS_TAG = 'ADDRESS'
ESCAPE_PHONE_TAG = 'PHONE'
ESCAPE_WEBSITE_TAG = 'WEBSITE'
ESCAPE_LAT_TAG = 'LAT'
ESCAPE_LON_TAG = 'LON'
ESCAPE_TAGS_TAG = 'TAGS'
ESCAPE_CODE_TAG = 'CODE'

ROOMS_TAG = 'ROOMS'

ROOMS_NAME_TAG = 'NAME'
ROOMS_WEBSITE_TAG = 'WEBSITE'
ROOMS_PRICES_TAG = 'PRICES'
ROOMS_AVAIL_TAG = 'AVAIL'
ROOMS_CODE_TAG = 'CODE'

# strings separator
SEPARATOR = '%'

# tags
HORROR_TAG = "horror"
ACTORS_TAG = "attori"
ADVENTURE_TAG = "avventura"
MISTERY_TAG = "thriller"
ACTION_TAG = "azione"
CAZZEGGIO_TAG = "cazzeggio"
