ESCAPES_TAG = 'ESCAPES'

ESCAPE_NAME_TAG = 'NAME'
ESCAPE_ADDRESS_TAG = 'ADDRESS'
ESCAPE_PHONE_TAG = 'PHONE'
ESCAPE_WEBSITE_TAG = 'WEBSITE'
ESCAPE_LAT_TAG = 'LAT'
ESCAPE_LON_TAG = 'LON'
ESCAPE_CODE_TAG = 'CODE'

ROOMS_TAG = 'ROOMS'

ROOMS_NAME_TAG = 'NAME'
ROOMS_WEBSITE_TAG = 'WEBSITE'
ROOMS_PRICES_TAG = 'PRICES'
ROOMS_AVAIL_TAG = 'AVAIL'
ROOMS_CODE_TAG = 'CODE'

SEPARATOR = '%'
